version: '3'
services:
  web:
    build: .
    command: yarn server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment: 
      REDIS_URL: 'redis'
      REDIS_PORT: 6379
  worker:
    build: .
    command: yarn worker
    depends_on:
      - redis
    environment: 
      REDIS_URL: 'redis'
      REDIS_PORT: 6379
  redis:
    image: redis
    expose:
      - 6379